name: Despliegue en EC2

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.12]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - run: npm ci
      - run: npm run test

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
            args: >
              -Dsonar.projectKey=henlo-mm_HOGARPRO-SERVICE
              -Dsonar.organization=henlo-mm
              -Dsonar.sources=.
              -Dsonar.host.url=https://sonarcloud.io
              -Dsonar.token=${{ secrets.SONAR_TOKEN }}
              -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            
      - run: npm run build
      # - run: npm run test
      - name: create .env
        run: |
          echo "TOKEN_SECRET=${{ secrets.SERVICE_TOKEN_SECRET }}" > ./build/src/.env
          echo "PATH_IMG=${{ secrets.SERVICE_PATH_IMG }}" >> ./build/src/.env
          echo "PATH_DOC=${{ secrets.SERVICE_PATH_DOC }}" >> ./build/src/.env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> ./build/src/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./build/src/.env

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/HOGARPRO-SERVICE/
          remote_host: "${{ secrets.EC2_HOST }}"
          remote_user: "${{ secrets.EC2_USERNAME }}"
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
